server:
  port: 9084
  error.include-message: always
  servlet:
    context-path: /codegen/

management:
  server:
    port: 9184

scribe:
  allow-list:
    - http://172.17.0.1:8080/orgs/*/projects/*/changesets/*
    - https://api.content-cloud.eu/orgs/*/projects/*/changesets/*
    - http://host.docker.internal:8080/orgs/*/projects/*/changesets/*

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.content-cloud.eu/auth/realms/contentcloud-console