server:
  port: 8081

initializr:
  group-id:
    value: eu.xenit.contentcloud.apps
  env:
    gradle:
      dependency-management-plugin-version: 1.0.11.RELEASE
    repositories:
      sonatype-snapshots:
        name: sonatype-snapshots
        url: https://oss.sonatype.org/content/repositories/snapshots/
  dependencies:
    - name: Developer Tools
      content:
        - name: Lombok
          id: lombok
          groupId: org.projectlombok
          artifactId: lombok
          scope: annotationProcessor
          description: Java annotation library which helps to reduce boilerplate code.
          facets:
            - native
          starter: false
    - name: Web
      content:
        - name: Web
          id: web
          description: Servlet web application with Spring MVC and Tomcat
        - name: Spring Data JPA
          id: data-jpa
          description: Persist data in SQL stores with Java Persistence API using Spring Data and Hibernate.
          facets:
            - jpa
            - native
          aliases:
            - jpa
          links:
            - rel: guide
              href: https://spring.io/guides/gs/accessing-data-jpa/
              description: Accessing Data with JPA
            - rel: reference
              href: https://docs.spring.io/spring-boot/docs/{bootVersion}/reference/htmlsingle/#boot-features-jpa-and-spring-data
        - name: Rest Repositories
          id: data-rest
          facets:
            - json
    - name: ContentCloud
      content:
        - name: Content Cloud Spring Boot Starter
          id: contentcloud-starter
          groupId: eu.xenit.contentcloud.starter
          artifactId: contentcloud-spring-boot-starter
          version: 0.1.0-SNAPSHOT
          facets:
            - contentcloud
        - name: Content Cloud Spring Boot Annotions Starter
          id: contentcloud-annotations-starter
          groupId: eu.xenit.contentcloud.starter
          artifactId: contentcloud-spring-boot-starter-annotations
          version: 0.1.0-SNAPSHOT
          scope: annotationProcessor
          repository: sonatype-snapshots
  languages:
    - name: Java
      id: java
      default: true
  javaVersions:
    - id: 11
      default: true
  packagings:
    - name: Jar
      id: jar
      default: true
  types:
    - name: Gradle Project
      id: gradle-project
      description: Generate a Gradle based project archive
      tags:
        build: gradle
        format: project
      default: true
      action: /starter.zip
  bootVersions:
    - name: 2.5.4
      id: 2.5.4
      default: true
